### ISSUE TITLE
Silence/mute plotting

### ISSUE THREAD

**Issue by JoshChristie** [c42f/Displaz.jl#2]
In debugging my code I tend to append a debug flag to functions that I would like to plot data in. It would be nice to set globally whether plots can be silenced/muted.  Is this a feature that would be useful or would it be adding more overhead?

Current typical usage:

``` julia
function main(debug_flag::Bool = false)
    dostuff(debug_flag)
end

function dostuff(debug_flag)
     debug_flag && plot3d!(rand(3,10000))
end
```

Proposed usage:

``` julia
function main(debug_flag::Bool = false)
    debug_flag == false && disable_plot()  # Have this at the start of top level function
    dostuff()
end

function dostuff()
     plot3d!(rand(3,10000))    # This won't do anything
end
```

**Comment by c42f** [comment]
Yes, this seems useful and wouldn't add any noticeable overhead.  However, what might be noticeable in your application code would be gathering plot information for plots which you don't actually end up displaying.  It also makes your application depend on the displaz package even in production... which is no major problem but perhaps slightly odd.

To avoid those problems this might be better as a macro, and not in the Displaz package itself: that way you don't even need Displaz.jl in the production build.

``` julia
debug_flag = false

macro debug_only(expr)
    debug_flag ? esc(expr) : :nothing
end

# ...
@debug_only using Displaz
# ...
@debug_only plot3d!(rand(3,100000))

@debug_only begin
    points = [#= some expensive computation =#]
    plot3d!(points)
end
```

The downside is that you probably can't set `debug_flag` from the main function in a clean way, since it affects code generation rather than being a runtime switch.

**Comment by c42f** [comment]
What did you think Josh?  Would the above solve your problem neatly, or do you want a flag which can be set dynamically?  Feel free to close the issue if you think it's sorted out.
